# Generated by Django 2.1 on 2018-12-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flitting', '0003_auto_20181201_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
