# Generated by Django 2.1 on 2018-12-01 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flitting', '0007_listing_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('rating', models.IntegerField()),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_helper', to=settings.AUTH_USER_MODEL)),
                ('newbie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_newbie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
