# Generated by Django 2.1 on 2018-12-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flitting', '0010_listing_profile_request_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='text',
        ),
    ]
