# Generated by Django 2.1 on 2018-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flitting', '0011_remove_request_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='startDate',
            field=models.DateField(),
        ),
    ]
