# Generated by Django 2.1 on 2018-12-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flitting', '0005_listing_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
