# Generated by Django 2.1 on 2018-12-01 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flitting', '0009_auto_20181201_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('phone', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('description', models.TextField()),
                ('isAccepted', models.BooleanField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request_helper', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flitting.Listing')),
                ('newbie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request_newbie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('rating', models.IntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_helper', to=settings.AUTH_USER_MODEL)),
                ('newbie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review_newbie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
